name = "fizzbuzzagain"
version = "0.1.0"
license = "license"
author = "Brad Richardson"
maintainer = "everythingfunctional@protonmail.com"
copyright = "Copyright 2022, Brad Richardson"

[dependencies]
strff = { git = "https://gitlab.com/everythingfunctional/strff", tag = "v4.0.0"}

[dev-dependencies]
veggies = { git = "https://gitlab.com/everythingfunctional/veggies", tag = "v1.0.5" }